#!/usr/bin/env bash
# bash script

info () {
	echo "$(dig www.$1 | awk '/ANSWER SECTION:/{getline; print"The subdomain www is a " $4 record and points to " $5}')"
	echo "$(dig web-01.$1 | awk '/ANSWER SECTION:/{getline; print"The subdomain web-02 is a " $4 record and points to " $5}')"
	echo "$(dig web-02.$1 | awk '/ANSWER SECTION:/{getline; print"The subdomain web-02 is a " $4 record and points to " $5}')"
	echo "$(dig 1b-01.$1 | awk '/ANSWER SECTION:/{getline; print"The subdomain 1b-01 is a " $4 record and points to " $5}')"	
}

if [ "$#" == 1];then
	info "$1"
fi

if [ "$#" == 2];then
	info "$1" "$2"
fi
