#!/usr/bin/env bash
# script that install nginx

sudo apt-get update
sudo apt-get install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
