#!/usr/bin/env bash
# a Bash script that gives you information about the school file.
file="school"
if [[ -e $file ]];then
	echo "school file exists"
	if [[ -n $file ]];then
		echo "school file is empty"
	elif [[ -z $file ]];then
		echo "school file is not empty"
	elif [[ -f $file ]];then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi	
